# Generated by Django 4.0.3 on 2022-04-15 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Post in event', 'verbose_name_plural': 'Posts in event'},
        ),
    ]
