# Generated by Django 4.0.3 on 2022-04-15 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post in blog', 'verbose_name_plural': 'Posts in blog'},
        ),
    ]
