# Generated by Django 4.0.3 on 2022-04-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=300, verbose_name='Name and last name')),
                ('about_image', models.ImageField(upload_to='event_images/')),
                ('about_text', models.TextField(verbose_name='Tell me abot you: ')),
            ],
        ),
    ]
